/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Clases.ClassJugador;
import Util.Lista;
import java.awt.Color;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.Queue;
import java.util.Stack;

import javax.swing.JPanel;

/**
 *
 * @author ARMENI
 */
public class formJuego extends javax.swing.JFrame {

    /**
     * Creates new form formJuego
     */
    
    Lista casillas = new Lista();
    

    
    ClassJugador jugador1 = new ClassJugador(1,Color.RED,"jugador1");
    ClassJugador jugador2 = new ClassJugador(-1,new java.awt.Color(255,204,0),"jugador2");
    ClassJugador jugador3 = new ClassJugador(-1,new java.awt.Color(102,204,0),"jugador3");
    ClassJugador jugador4 = new ClassJugador(-1,new java.awt.Color(102,0,204),"jugador4");
    
    Queue jugadores = new LinkedList();
    


    public formJuego() {
        initComponents();
        this.setVisible(true);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        jLabelJugador3.setVisible(false);
        jLabelDinero3.setVisible(false);
        jLabelBillete3.setVisible(false);
        jLabelJugador4.setVisible(false);
        jLabelDinero4.setVisible(false);
        jLabelBillete4.setVisible(false);
      
        asignar();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelJuego = new javax.swing.JPanel();
        X = new javax.swing.JLabel();
        jPanelCarcel = new javax.swing.JPanel();
        jPanelGo = new javax.swing.JPanel();
        jScroll = new javax.swing.JScrollPane();
        jTextArea = new javax.swing.JTextArea();
        jPanelAvNewYork = new javax.swing.JPanel();
        jPanelAvTennesse = new javax.swing.JPanel();
        jPanelFerroPensilvania = new javax.swing.JPanel();
        jPanelArcaComunal2 = new javax.swing.JPanel();
        jPanelPlazaJames = new javax.swing.JPanel();
        jPanelAvVirginia = new javax.swing.JPanel();
        jPanelAvStatus = new javax.swing.JPanel();
        jPanelElectricidad = new javax.swing.JPanel();
        jPanelPlazaSanCarlos = new javax.swing.JPanel();
        jPanelDescanso = new javax.swing.JPanel();
        jPanelBase = new javax.swing.JPanel();
        tirarDados = new javax.swing.JButton();
        jLabelResultadoDado = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanelAvKentucky = new javax.swing.JPanel();
        jPanelSuerte2 = new javax.swing.JPanel();
        jPanelAvIndiana = new javax.swing.JPanel();
        jPanelAvIllinois = new javax.swing.JPanel();
        jPanelFerroByO = new javax.swing.JPanel();
        jPanelAvAtlantico = new javax.swing.JPanel();
        jPanelAvVentnor = new javax.swing.JPanel();
        jPanelAgua = new javax.swing.JPanel();
        jPanelJardinesMarvin = new javax.swing.JPanel();
        jPanelIrACarcel = new javax.swing.JPanel();
        jPanelAvPacifico = new javax.swing.JPanel();
        jPanelAvCarolinaNorte = new javax.swing.JPanel();
        jPanelArcaComunal3 = new javax.swing.JPanel();
        jPanelAvPensilvania = new javax.swing.JPanel();
        jPanelFerroViaRapida = new javax.swing.JPanel();
        jPanelSuerte3 = new javax.swing.JPanel();
        jPanelPlazaPark = new javax.swing.JPanel();
        jPanelImpuestoLujo = new javax.swing.JPanel();
        jPanelMuelle = new javax.swing.JPanel();
        jPanelAvConnecticut = new javax.swing.JPanel();
        jPanelAvOriental = new javax.swing.JPanel();
        jScroll4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jPanelAvMediterraneo = new javax.swing.JPanel();
        jScroll1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanelSuerte1 = new javax.swing.JPanel();
        jPanelAvVermont = new javax.swing.JPanel();
        jPanelAvBaltica = new javax.swing.JPanel();
        jScroll3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jPanelFerroReading = new javax.swing.JPanel();
        jScroll6 = new javax.swing.JScrollPane();
        jTextArea6 = new javax.swing.JTextArea();
        jPanelArcaComunal1 = new javax.swing.JPanel();
        jScroll2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jPanelImpuestoIngresos = new javax.swing.JPanel();
        jScroll5 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabelDinero4 = new javax.swing.JLabel();
        jLabelDinero3 = new javax.swing.JLabel();
        jLabelBillete3 = new javax.swing.JLabel();
        jLabelJugador1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabelJugador2 = new javax.swing.JLabel();
        jLabelJugador3 = new javax.swing.JLabel();
        jLabelBillete4 = new javax.swing.JLabel();
        jLabelJugador4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelJuego.setBackground(new java.awt.Color(255, 255, 255));
        panelJuego.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        X.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        X.setText("X");
        X.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                XMouseClicked(evt);
            }
        });
        panelJuego.add(X, new org.netbeans.lib.awtextra.AbsoluteConstraints(1390, 0, 20, 20));

        jPanelCarcel.setBackground(new java.awt.Color(220, 245, 245));
        jPanelCarcel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanelCarcelLayout = new javax.swing.GroupLayout(jPanelCarcel);
        jPanelCarcel.setLayout(jPanelCarcelLayout);
        jPanelCarcelLayout.setHorizontalGroup(
            jPanelCarcelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );
        jPanelCarcelLayout.setVerticalGroup(
            jPanelCarcelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );

        panelJuego.add(jPanelCarcel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 630, 80, 80));

        jPanelGo.setBackground(new java.awt.Color(220, 245, 245));
        jPanelGo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jScroll.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScroll.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea.setEditable(false);
        jTextArea.setBackground(new java.awt.Color(220, 245, 245));
        jTextArea.setColumns(20);
        jTextArea.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jTextArea.setRows(5);
        jTextArea.setText("GO\nCÓBRENSE\n$200 DE\nSUELDO AL\nPASAR");
        jScroll.setViewportView(jTextArea);

        javax.swing.GroupLayout jPanelGoLayout = new javax.swing.GroupLayout(jPanelGo);
        jPanelGo.setLayout(jPanelGoLayout);
        jPanelGoLayout.setHorizontalGroup(
            jPanelGoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelGoLayout.setVerticalGroup(
            jPanelGoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScroll)
                .addContainerGap())
        );

        panelJuego.add(jPanelGo, new org.netbeans.lib.awtextra.AbsoluteConstraints(984, 630, 80, 80));

        jPanelAvNewYork.setBackground(new java.awt.Color(220, 245, 245));
        jPanelAvNewYork.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanelAvNewYorkLayout = new javax.swing.GroupLayout(jPanelAvNewYork);
        jPanelAvNewYork.setLayout(jPanelAvNewYorkLayout);
        jPanelAvNewYorkLayout.setHorizontalGroup(
            jPanelAvNewYorkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );
        jPanelAvNewYorkLayout.setVerticalGroup(
            jPanelAvNewYorkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );

        panelJuego.add(jPanelAvNewYork, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 80, 60));

        jPanelAvTennesse.setBackground(new java.awt.Color(220, 245, 245));
        jPanelAvTennesse.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanelAvTennesseLayout = new javax.swing.GroupLayout(jPanelAvTennesse);
        jPanelAvTennesse.setLayout(jPanelAvTennesseLayout);
        jPanelAvTennesseLayout.setHorizontalGroup(
            jPanelAvTennesseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );
        jPanelAvTennesseLayout.setVerticalGroup(
            jPanelAvTennesseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );

        panelJuego.add(jPanelAvTennesse, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 80, 60));

        jPanelFerroPensilvania.setBackground(new java.awt.Color(220, 245, 245));
        jPanelFerroPensilvania.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanelFerroPensilvaniaLayout = new javax.swing.GroupLayout(jPanelFerroPensilvania);
        jPanelFerroPensilvania.setLayout(jPanelFerroPensilvaniaLayout);
        jPanelFerroPensilvaniaLayout.setHorizontalGroup(
            jPanelFerroPensilvaniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );
        jPanelFerroPensilvaniaLayout.setVerticalGroup(
            jPanelFerroPensilvaniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );

        panelJuego.add(jPanelFerroPensilvania, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, 80, 60));

        jPanelArcaComunal2.setBackground(new java.awt.Color(220, 245, 245));
        jPanelArcaComunal2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanelArcaComunal2Layout = new javax.swing.GroupLayout(jPanelArcaComunal2);
        jPanelArcaComunal2.setLayout(jPanelArcaComunal2Layout);
        jPanelArcaComunal2Layout.setHorizontalGroup(
            jPanelArcaComunal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );
        jPanelArcaComunal2Layout.setVerticalGroup(
            jPanelArcaComunal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );

        panelJuego.add(jPanelArcaComunal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 80, 60));

        jPanelPlazaJames.setBackground(new java.awt.Color(220, 245, 245));
        jPanelPlazaJames.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanelPlazaJamesLayout = new javax.swing.GroupLayout(jPanelPlazaJames);
        jPanelPlazaJames.setLayout(jPanelPlazaJamesLayout);
        jPanelPlazaJamesLayout.setHorizontalGroup(
            jPanelPlazaJamesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );
        jPanelPlazaJamesLayout.setVerticalGroup(
            jPanelPlazaJamesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );

        panelJuego.add(jPanelPlazaJames, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, 80, 60));

        jPanelAvVirginia.setBackground(new java.awt.Color(220, 245, 245));
        jPanelAvVirginia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanelAvVirginiaLayout = new javax.swing.GroupLayout(jPanelAvVirginia);
        jPanelAvVirginia.setLayout(jPanelAvVirginiaLayout);
        jPanelAvVirginiaLayout.setHorizontalGroup(
            jPanelAvVirginiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );
        jPanelAvVirginiaLayout.setVerticalGroup(
            jPanelAvVirginiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );

        panelJuego.add(jPanelAvVirginia, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 390, 80, 60));

        jPanelAvStatus.setBackground(new java.awt.Color(220, 245, 245));
        jPanelAvStatus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanelAvStatusLayout = new javax.swing.GroupLayout(jPanelAvStatus);
        jPanelAvStatus.setLayout(jPanelAvStatusLayout);
        jPanelAvStatusLayout.setHorizontalGroup(
            jPanelAvStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );
        jPanelAvStatusLayout.setVerticalGroup(
            jPanelAvStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );

        panelJuego.add(jPanelAvStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 450, 80, 60));

        jPanelElectricidad.setBackground(new java.awt.Color(220, 245, 245));
        jPanelElectricidad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanelElectricidadLayout = new javax.swing.GroupLayout(jPanelElectricidad);
        jPanelElectricidad.setLayout(jPanelElectricidadLayout);
        jPanelElectricidadLayout.setHorizontalGroup(
            jPanelElectricidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );
        jPanelElectricidadLayout.setVerticalGroup(
            jPanelElectricidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );

        panelJuego.add(jPanelElectricidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 510, 80, 60));

        jPanelPlazaSanCarlos.setBackground(new java.awt.Color(220, 245, 245));
        jPanelPlazaSanCarlos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanelPlazaSanCarlosLayout = new javax.swing.GroupLayout(jPanelPlazaSanCarlos);
        jPanelPlazaSanCarlos.setLayout(jPanelPlazaSanCarlosLayout);
        jPanelPlazaSanCarlosLayout.setHorizontalGroup(
            jPanelPlazaSanCarlosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );
        jPanelPlazaSanCarlosLayout.setVerticalGroup(
            jPanelPlazaSanCarlosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );

        panelJuego.add(jPanelPlazaSanCarlos, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 570, 80, 60));

        jPanelDescanso.setBackground(new java.awt.Color(220, 245, 245));
        jPanelDescanso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanelDescansoLayout = new javax.swing.GroupLayout(jPanelDescanso);
        jPanelDescanso.setLayout(jPanelDescansoLayout);
        jPanelDescansoLayout.setHorizontalGroup(
            jPanelDescansoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );
        jPanelDescansoLayout.setVerticalGroup(
            jPanelDescansoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );

        panelJuego.add(jPanelDescanso, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 80, 80));

        jPanelBase.setBackground(new java.awt.Color(242, 249, 249));
        jPanelBase.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelBase.setPreferredSize(new java.awt.Dimension(555, 540));
        jPanelBase.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tirarDados.setText("TIRAR DADOS");
        tirarDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tirarDadosActionPerformed(evt);
            }
        });
        jPanelBase.add(tirarDados, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 460, -1, -1));

        jLabelResultadoDado.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 36)); // NOI18N
        jLabelResultadoDado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelBase.add(jLabelResultadoDado, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, 60, 50));

        jLabel1.setBackground(new java.awt.Color(153, 0, 153));
        jLabel1.setFont(new java.awt.Font("Goudy Stout", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 102));
        jLabel1.setText("VIRTUAL MONOPOLY");
        jPanelBase.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 500, 90));

        panelJuego.add(jPanelBase, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, 554, 540));

        jPanelAvKentucky.setBackground(new java.awt.Color(220, 245, 245));
        jPanelAvKentucky.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanelAvKentuckyLayout = new javax.swing.GroupLayout(jPanelAvKentucky);
        jPanelAvKentucky.setLayout(jPanelAvKentuckyLayout);
        jPanelAvKentuckyLayout.setHorizontalGroup(
            jPanelAvKentuckyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );
        jPanelAvKentuckyLayout.setVerticalGroup(
            jPanelAvKentuckyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );

        panelJuego.add(jPanelAvKentucky, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 60, 80));

        jPanelSuerte2.setBackground(new java.awt.Color(220, 245, 245));
        jPanelSuerte2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanelSuerte2Layout = new javax.swing.GroupLayout(jPanelSuerte2);
        jPanelSuerte2.setLayout(jPanelSuerte2Layout);
        jPanelSuerte2Layout.setHorizontalGroup(
            jPanelSuerte2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        jPanelSuerte2Layout.setVerticalGroup(
            jPanelSuerte2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );

        panelJuego.add(jPanelSuerte2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, -1, 80));

        jPanelAvIndiana.setBackground(new java.awt.Color(220, 245, 245));
        jPanelAvIndiana.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanelAvIndianaLayout = new javax.swing.GroupLayout(jPanelAvIndiana);
        jPanelAvIndiana.setLayout(jPanelAvIndianaLayout);
        jPanelAvIndianaLayout.setHorizontalGroup(
            jPanelAvIndianaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        jPanelAvIndianaLayout.setVerticalGroup(
            jPanelAvIndianaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );

        panelJuego.add(jPanelAvIndiana, new org.netbeans.lib.awtextra.AbsoluteConstraints(552, 10, -1, 80));

        jPanelAvIllinois.setBackground(new java.awt.Color(220, 245, 245));
        jPanelAvIllinois.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanelAvIllinoisLayout = new javax.swing.GroupLayout(jPanelAvIllinois);
        jPanelAvIllinois.setLayout(jPanelAvIllinoisLayout);
        jPanelAvIllinoisLayout.setHorizontalGroup(
            jPanelAvIllinoisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        jPanelAvIllinoisLayout.setVerticalGroup(
            jPanelAvIllinoisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );

        panelJuego.add(jPanelAvIllinois, new org.netbeans.lib.awtextra.AbsoluteConstraints(614, 10, -1, 80));

        jPanelFerroByO.setBackground(new java.awt.Color(220, 245, 245));
        jPanelFerroByO.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanelFerroByOLayout = new javax.swing.GroupLayout(jPanelFerroByO);
        jPanelFerroByO.setLayout(jPanelFerroByOLayout);
        jPanelFerroByOLayout.setHorizontalGroup(
            jPanelFerroByOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        jPanelFerroByOLayout.setVerticalGroup(
            jPanelFerroByOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );

        panelJuego.add(jPanelFerroByO, new org.netbeans.lib.awtextra.AbsoluteConstraints(676, 10, -1, 80));

        jPanelAvAtlantico.setBackground(new java.awt.Color(220, 245, 245));
        jPanelAvAtlantico.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanelAvAtlanticoLayout = new javax.swing.GroupLayout(jPanelAvAtlantico);
        jPanelAvAtlantico.setLayout(jPanelAvAtlanticoLayout);
        jPanelAvAtlanticoLayout.setHorizontalGroup(
            jPanelAvAtlanticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        jPanelAvAtlanticoLayout.setVerticalGroup(
            jPanelAvAtlanticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );

        panelJuego.add(jPanelAvAtlantico, new org.netbeans.lib.awtextra.AbsoluteConstraints(738, 10, -1, 80));

        jPanelAvVentnor.setBackground(new java.awt.Color(220, 245, 245));
        jPanelAvVentnor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanelAvVentnorLayout = new javax.swing.GroupLayout(jPanelAvVentnor);
        jPanelAvVentnor.setLayout(jPanelAvVentnorLayout);
        jPanelAvVentnorLayout.setHorizontalGroup(
            jPanelAvVentnorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        jPanelAvVentnorLayout.setVerticalGroup(
            jPanelAvVentnorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );

        panelJuego.add(jPanelAvVentnor, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 10, -1, 80));

        jPanelAgua.setBackground(new java.awt.Color(220, 245, 245));
        jPanelAgua.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanelAguaLayout = new javax.swing.GroupLayout(jPanelAgua);
        jPanelAgua.setLayout(jPanelAguaLayout);
        jPanelAguaLayout.setHorizontalGroup(
            jPanelAguaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        jPanelAguaLayout.setVerticalGroup(
            jPanelAguaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );

        panelJuego.add(jPanelAgua, new org.netbeans.lib.awtextra.AbsoluteConstraints(862, 10, -1, 80));

        jPanelJardinesMarvin.setBackground(new java.awt.Color(220, 245, 245));
        jPanelJardinesMarvin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanelJardinesMarvinLayout = new javax.swing.GroupLayout(jPanelJardinesMarvin);
        jPanelJardinesMarvin.setLayout(jPanelJardinesMarvinLayout);
        jPanelJardinesMarvinLayout.setHorizontalGroup(
            jPanelJardinesMarvinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );
        jPanelJardinesMarvinLayout.setVerticalGroup(
            jPanelJardinesMarvinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );

        panelJuego.add(jPanelJardinesMarvin, new org.netbeans.lib.awtextra.AbsoluteConstraints(924, 10, -1, 80));

        jPanelIrACarcel.setBackground(new java.awt.Color(220, 245, 245));
        jPanelIrACarcel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanelIrACarcelLayout = new javax.swing.GroupLayout(jPanelIrACarcel);
        jPanelIrACarcel.setLayout(jPanelIrACarcelLayout);
        jPanelIrACarcelLayout.setHorizontalGroup(
            jPanelIrACarcelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );
        jPanelIrACarcelLayout.setVerticalGroup(
            jPanelIrACarcelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );

        panelJuego.add(jPanelIrACarcel, new org.netbeans.lib.awtextra.AbsoluteConstraints(984, 10, 80, 80));

        jPanelAvPacifico.setBackground(new java.awt.Color(220, 245, 245));
        jPanelAvPacifico.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanelAvPacificoLayout = new javax.swing.GroupLayout(jPanelAvPacifico);
        jPanelAvPacifico.setLayout(jPanelAvPacificoLayout);
        jPanelAvPacificoLayout.setHorizontalGroup(
            jPanelAvPacificoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );
        jPanelAvPacificoLayout.setVerticalGroup(
            jPanelAvPacificoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );

        panelJuego.add(jPanelAvPacifico, new org.netbeans.lib.awtextra.AbsoluteConstraints(984, 90, 80, 60));

        jPanelAvCarolinaNorte.setBackground(new java.awt.Color(220, 245, 245));
        jPanelAvCarolinaNorte.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanelAvCarolinaNorteLayout = new javax.swing.GroupLayout(jPanelAvCarolinaNorte);
        jPanelAvCarolinaNorte.setLayout(jPanelAvCarolinaNorteLayout);
        jPanelAvCarolinaNorteLayout.setHorizontalGroup(
            jPanelAvCarolinaNorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );
        jPanelAvCarolinaNorteLayout.setVerticalGroup(
            jPanelAvCarolinaNorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );

        panelJuego.add(jPanelAvCarolinaNorte, new org.netbeans.lib.awtextra.AbsoluteConstraints(984, 150, 80, 60));

        jPanelArcaComunal3.setBackground(new java.awt.Color(220, 245, 245));
        jPanelArcaComunal3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanelArcaComunal3Layout = new javax.swing.GroupLayout(jPanelArcaComunal3);
        jPanelArcaComunal3.setLayout(jPanelArcaComunal3Layout);
        jPanelArcaComunal3Layout.setHorizontalGroup(
            jPanelArcaComunal3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );
        jPanelArcaComunal3Layout.setVerticalGroup(
            jPanelArcaComunal3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );

        panelJuego.add(jPanelArcaComunal3, new org.netbeans.lib.awtextra.AbsoluteConstraints(984, 210, 80, 60));

        jPanelAvPensilvania.setBackground(new java.awt.Color(220, 245, 245));
        jPanelAvPensilvania.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanelAvPensilvaniaLayout = new javax.swing.GroupLayout(jPanelAvPensilvania);
        jPanelAvPensilvania.setLayout(jPanelAvPensilvaniaLayout);
        jPanelAvPensilvaniaLayout.setHorizontalGroup(
            jPanelAvPensilvaniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );
        jPanelAvPensilvaniaLayout.setVerticalGroup(
            jPanelAvPensilvaniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );

        panelJuego.add(jPanelAvPensilvania, new org.netbeans.lib.awtextra.AbsoluteConstraints(984, 270, 80, 60));

        jPanelFerroViaRapida.setBackground(new java.awt.Color(220, 245, 245));
        jPanelFerroViaRapida.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelFerroViaRapida.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelJuego.add(jPanelFerroViaRapida, new org.netbeans.lib.awtextra.AbsoluteConstraints(984, 330, 80, 60));

        jPanelSuerte3.setBackground(new java.awt.Color(220, 245, 245));
        jPanelSuerte3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanelSuerte3Layout = new javax.swing.GroupLayout(jPanelSuerte3);
        jPanelSuerte3.setLayout(jPanelSuerte3Layout);
        jPanelSuerte3Layout.setHorizontalGroup(
            jPanelSuerte3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );
        jPanelSuerte3Layout.setVerticalGroup(
            jPanelSuerte3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );

        panelJuego.add(jPanelSuerte3, new org.netbeans.lib.awtextra.AbsoluteConstraints(984, 390, 80, 60));

        jPanelPlazaPark.setBackground(new java.awt.Color(220, 245, 245));
        jPanelPlazaPark.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanelPlazaParkLayout = new javax.swing.GroupLayout(jPanelPlazaPark);
        jPanelPlazaPark.setLayout(jPanelPlazaParkLayout);
        jPanelPlazaParkLayout.setHorizontalGroup(
            jPanelPlazaParkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );
        jPanelPlazaParkLayout.setVerticalGroup(
            jPanelPlazaParkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );

        panelJuego.add(jPanelPlazaPark, new org.netbeans.lib.awtextra.AbsoluteConstraints(984, 450, 80, 60));

        jPanelImpuestoLujo.setBackground(new java.awt.Color(220, 245, 245));
        jPanelImpuestoLujo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanelImpuestoLujoLayout = new javax.swing.GroupLayout(jPanelImpuestoLujo);
        jPanelImpuestoLujo.setLayout(jPanelImpuestoLujoLayout);
        jPanelImpuestoLujoLayout.setHorizontalGroup(
            jPanelImpuestoLujoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );
        jPanelImpuestoLujoLayout.setVerticalGroup(
            jPanelImpuestoLujoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );

        panelJuego.add(jPanelImpuestoLujo, new org.netbeans.lib.awtextra.AbsoluteConstraints(984, 510, 80, 60));

        jPanelMuelle.setBackground(new java.awt.Color(220, 245, 245));
        jPanelMuelle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanelMuelleLayout = new javax.swing.GroupLayout(jPanelMuelle);
        jPanelMuelle.setLayout(jPanelMuelleLayout);
        jPanelMuelleLayout.setHorizontalGroup(
            jPanelMuelleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );
        jPanelMuelleLayout.setVerticalGroup(
            jPanelMuelleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );

        panelJuego.add(jPanelMuelle, new org.netbeans.lib.awtextra.AbsoluteConstraints(984, 570, 80, 60));

        jPanelAvConnecticut.setBackground(new java.awt.Color(220, 245, 245));
        jPanelAvConnecticut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanelAvConnecticutLayout = new javax.swing.GroupLayout(jPanelAvConnecticut);
        jPanelAvConnecticut.setLayout(jPanelAvConnecticutLayout);
        jPanelAvConnecticutLayout.setHorizontalGroup(
            jPanelAvConnecticutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );
        jPanelAvConnecticutLayout.setVerticalGroup(
            jPanelAvConnecticutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );

        panelJuego.add(jPanelAvConnecticut, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 630, -1, -1));

        jPanelAvOriental.setBackground(new java.awt.Color(220, 245, 245));
        jPanelAvOriental.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelAvOriental.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScroll4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScroll4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea4.setEditable(false);
        jTextArea4.setBackground(new java.awt.Color(220, 245, 245));
        jTextArea4.setColumns(20);
        jTextArea4.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jTextArea4.setRows(5);
        jTextArea4.setText("AV\nORIENTAL\n\n$100");
        jScroll4.setViewportView(jTextArea4);

        jPanelAvOriental.add(jScroll4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 60, 60));

        panelJuego.add(jPanelAvOriental, new org.netbeans.lib.awtextra.AbsoluteConstraints(614, 630, 62, 80));

        jPanelAvMediterraneo.setBackground(new java.awt.Color(220, 245, 245));
        jPanelAvMediterraneo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelAvMediterraneo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScroll1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScroll1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(220, 245, 245));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("AV\nMEDITER-\nRÁNEO\n\n$60");
        jScroll1.setViewportView(jTextArea1);

        jPanelAvMediterraneo.add(jScroll1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 60));

        panelJuego.add(jPanelAvMediterraneo, new org.netbeans.lib.awtextra.AbsoluteConstraints(922, 630, 62, 80));

        jPanelSuerte1.setBackground(new java.awt.Color(220, 245, 245));
        jPanelSuerte1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanelSuerte1Layout = new javax.swing.GroupLayout(jPanelSuerte1);
        jPanelSuerte1.setLayout(jPanelSuerte1Layout);
        jPanelSuerte1Layout.setHorizontalGroup(
            jPanelSuerte1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        jPanelSuerte1Layout.setVerticalGroup(
            jPanelSuerte1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );

        panelJuego.add(jPanelSuerte1, new org.netbeans.lib.awtextra.AbsoluteConstraints(552, 630, -1, -1));

        jPanelAvVermont.setBackground(new java.awt.Color(220, 245, 245));
        jPanelAvVermont.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanelAvVermontLayout = new javax.swing.GroupLayout(jPanelAvVermont);
        jPanelAvVermont.setLayout(jPanelAvVermontLayout);
        jPanelAvVermontLayout.setHorizontalGroup(
            jPanelAvVermontLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        jPanelAvVermontLayout.setVerticalGroup(
            jPanelAvVermontLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );

        panelJuego.add(jPanelAvVermont, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 630, -1, 80));

        jPanelAvBaltica.setBackground(new java.awt.Color(220, 245, 245));
        jPanelAvBaltica.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelAvBaltica.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScroll3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScroll3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea3.setEditable(false);
        jTextArea3.setBackground(new java.awt.Color(220, 245, 245));
        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jTextArea3.setRows(5);
        jTextArea3.setText("AV\nBALTICA\n\n$60\n");
        jScroll3.setViewportView(jTextArea3);

        jPanelAvBaltica.add(jScroll3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 60));

        panelJuego.add(jPanelAvBaltica, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 630, 62, 80));

        jPanelFerroReading.setBackground(new java.awt.Color(220, 245, 245));
        jPanelFerroReading.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelFerroReading.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScroll6.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScroll6.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea6.setEditable(false);
        jTextArea6.setBackground(new java.awt.Color(220, 245, 245));
        jTextArea6.setColumns(20);
        jTextArea6.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jTextArea6.setRows(5);
        jTextArea6.setText("FERRO-\nCARRIL\nREADING\n\n$200");
        jScroll6.setViewportView(jTextArea6);

        jPanelFerroReading.add(jScroll6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 30, 60));

        panelJuego.add(jPanelFerroReading, new org.netbeans.lib.awtextra.AbsoluteConstraints(676, 630, 62, 80));

        jPanelArcaComunal1.setBackground(new java.awt.Color(220, 245, 245));
        jPanelArcaComunal1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelArcaComunal1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScroll2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScroll2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea2.setEditable(false);
        jTextArea2.setBackground(new java.awt.Color(220, 245, 245));
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jTextArea2.setRows(5);
        jTextArea2.setText("ARCA\nCOMUNAL");
        jScroll2.setViewportView(jTextArea2);

        jPanelArcaComunal1.add(jScroll2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 60));

        panelJuego.add(jPanelArcaComunal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(862, 630, 60, 80));

        jPanelImpuestoIngresos.setBackground(new java.awt.Color(220, 245, 245));
        jPanelImpuestoIngresos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelImpuestoIngresos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScroll5.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScroll5.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea5.setEditable(false);
        jTextArea5.setBackground(new java.awt.Color(220, 245, 245));
        jTextArea5.setColumns(20);
        jTextArea5.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jTextArea5.setRows(5);
        jTextArea5.setText("IMPUESTO\nSOBRE\nINGRESO\n\n$200");
        jScroll5.setViewportView(jTextArea5);

        jPanelImpuestoIngresos.add(jScroll5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 60));

        panelJuego.add(jPanelImpuestoIngresos, new org.netbeans.lib.awtextra.AbsoluteConstraints(738, 630, 62, 80));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("1500");
        panelJuego.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, 90, 50));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("1500");
        panelJuego.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 560, 90, 50));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setText("1500");
        panelJuego.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 560, 90, 50));

        jLabelDinero4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelDinero4.setText("1500");
        panelJuego.add(jLabelDinero4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 660, 90, 50));

        jLabelDinero3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelDinero3.setText("1500");
        panelJuego.add(jLabelDinero3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 660, 90, 50));

        jLabelBillete3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/icons8-billetes-48.png"))); // NOI18N
        panelJuego.add(jLabelBillete3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 660, 60, 40));

        jLabelJugador1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelJugador1.setForeground(new java.awt.Color(255, 0, 0));
        jLabelJugador1.setText("JUGADOR 1");
        jLabelJugador1.setToolTipText("");
        jLabelJugador1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabelJugador1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 5));
        jLabelJugador1.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jLabelJugador1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelJugador1MouseClicked(evt);
            }
        });
        panelJuego.add(jLabelJugador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 150, 80));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/icons8-billetes-48.png"))); // NOI18N
        panelJuego.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 560, 60, 40));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/icons8-billetes-48.png"))); // NOI18N
        panelJuego.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 560, 60, 40));

        jLabelJugador2.setBackground(new java.awt.Color(255, 204, 0));
        jLabelJugador2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelJugador2.setForeground(new java.awt.Color(255, 204, 0));
        jLabelJugador2.setText("JUGADOR 2");
        jLabelJugador2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabelJugador2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0), 5));
        panelJuego.add(jLabelJugador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 530, 150, 80));

        jLabelJugador3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelJugador3.setForeground(new java.awt.Color(102, 204, 0));
        jLabelJugador3.setText("JUGADOR 3");
        jLabelJugador3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabelJugador3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 204, 0), 5, true));
        panelJuego.add(jLabelJugador3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 630, 150, 80));

        jLabelBillete4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/icons8-billetes-48.png"))); // NOI18N
        panelJuego.add(jLabelBillete4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 660, 60, 40));

        jLabelJugador4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelJugador4.setForeground(new java.awt.Color(102, 0, 204));
        jLabelJugador4.setText("JUGADOR 4");
        jLabelJugador4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabelJugador4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 204), 5));
        panelJuego.add(jLabelJugador4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 630, 150, 80));

        getContentPane().add(panelJuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1410, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void XMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_XMouseClicked
        System.exit(0);
    }//GEN-LAST:event_XMouseClicked

    
    private void tirarDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tirarDadosActionPerformed
        
         
    }//GEN-LAST:event_tirarDadosActionPerformed

    private void jLabelJugador1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelJugador1MouseClicked
       
    }//GEN-LAST:event_jLabelJugador1MouseClicked

    public void agregarJugadores(){
        jugadores.add(jugador1);
        jugadores.add(jugador2);
        
        if(Integer.parseInt(formInicio.message)==3){
            jugadores.add(jugador3);
        } 
        
        if(Integer.parseInt(formInicio.message)==4){
            jugadores.add(jugador3);
            jugadores.add(jugador4);
        } 
        
    }
    public void asignar(){
        casillas.add(jPanelGo);
        casillas.add(jPanelAvMediterraneo);
        casillas.add(jPanelArcaComunal1);
        casillas.add(jPanelAvBaltica);
        casillas.add(jPanelImpuestoIngresos);
        casillas.add(jPanelFerroReading);
        casillas.add(jPanelAvOriental);
        casillas.add(jPanelSuerte1);
        casillas.add(jPanelAvVermont);
        casillas.add(jPanelAvConnecticut);
        casillas.add(jPanelCarcel);
        casillas.add(jPanelPlazaSanCarlos);
        casillas.add(jPanelElectricidad);
        casillas.add(jPanelAvStatus);
        casillas.add(jPanelAvVirginia);
        casillas.add(jPanelFerroPensilvania);
        casillas.add(jPanelPlazaJames);
        casillas.add(jPanelArcaComunal2);
        casillas.add(jPanelAvTennesse);
        casillas.add(jPanelAvNewYork);
        casillas.add(jPanelDescanso);
        casillas.add(jPanelAvKentucky);
        casillas.add(jPanelSuerte2);
        casillas.add(jPanelAvIndiana);
        casillas.add(jPanelAvIllinois);
        casillas.add(jPanelFerroByO);
        casillas.add(jPanelAvAtlantico);
        casillas.add(jPanelAvVentnor);
        casillas.add(jPanelAgua);
        casillas.add(jPanelJardinesMarvin);
        casillas.add(jPanelIrACarcel);
        casillas.add(jPanelAvPacifico);
        casillas.add(jPanelAvCarolinaNorte);
        casillas.add(jPanelArcaComunal3);
        casillas.add(jPanelAvPensilvania);
        casillas.add(jPanelFerroViaRapida);
        casillas.add(jPanelSuerte3);
        casillas.add(jPanelPlazaPark);
        casillas.add(jPanelImpuestoLujo);
        casillas.add(jPanelMuelle); 
    }
    

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formJuego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel X;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    protected static javax.swing.JLabel jLabelBillete3;
    protected static javax.swing.JLabel jLabelBillete4;
    public static javax.swing.JLabel jLabelDinero3;
    protected static javax.swing.JLabel jLabelDinero4;
    public javax.swing.JLabel jLabelJugador1;
    private javax.swing.JLabel jLabelJugador2;
    public static javax.swing.JLabel jLabelJugador3;
    protected static javax.swing.JLabel jLabelJugador4;
    public static javax.swing.JLabel jLabelResultadoDado;
    private javax.swing.JPanel jPanelAgua;
    private javax.swing.JPanel jPanelArcaComunal1;
    private javax.swing.JPanel jPanelArcaComunal2;
    private javax.swing.JPanel jPanelArcaComunal3;
    private javax.swing.JPanel jPanelAvAtlantico;
    private javax.swing.JPanel jPanelAvBaltica;
    private javax.swing.JPanel jPanelAvCarolinaNorte;
    private javax.swing.JPanel jPanelAvConnecticut;
    private javax.swing.JPanel jPanelAvIllinois;
    private javax.swing.JPanel jPanelAvIndiana;
    private javax.swing.JPanel jPanelAvKentucky;
    private javax.swing.JPanel jPanelAvMediterraneo;
    private javax.swing.JPanel jPanelAvNewYork;
    private javax.swing.JPanel jPanelAvOriental;
    private javax.swing.JPanel jPanelAvPacifico;
    private javax.swing.JPanel jPanelAvPensilvania;
    private javax.swing.JPanel jPanelAvStatus;
    private javax.swing.JPanel jPanelAvTennesse;
    private javax.swing.JPanel jPanelAvVentnor;
    private javax.swing.JPanel jPanelAvVermont;
    private javax.swing.JPanel jPanelAvVirginia;
    private javax.swing.JPanel jPanelBase;
    private javax.swing.JPanel jPanelCarcel;
    private javax.swing.JPanel jPanelDescanso;
    private javax.swing.JPanel jPanelElectricidad;
    private javax.swing.JPanel jPanelFerroByO;
    private javax.swing.JPanel jPanelFerroPensilvania;
    private javax.swing.JPanel jPanelFerroReading;
    private javax.swing.JPanel jPanelFerroViaRapida;
    private javax.swing.JPanel jPanelGo;
    private javax.swing.JPanel jPanelImpuestoIngresos;
    private javax.swing.JPanel jPanelImpuestoLujo;
    private javax.swing.JPanel jPanelIrACarcel;
    private javax.swing.JPanel jPanelJardinesMarvin;
    private javax.swing.JPanel jPanelMuelle;
    private javax.swing.JPanel jPanelPlazaJames;
    private javax.swing.JPanel jPanelPlazaPark;
    private javax.swing.JPanel jPanelPlazaSanCarlos;
    private javax.swing.JPanel jPanelSuerte1;
    private javax.swing.JPanel jPanelSuerte2;
    private javax.swing.JPanel jPanelSuerte3;
    private javax.swing.JScrollPane jScroll;
    private javax.swing.JScrollPane jScroll1;
    private javax.swing.JScrollPane jScroll2;
    private javax.swing.JScrollPane jScroll3;
    private javax.swing.JScrollPane jScroll4;
    private javax.swing.JScrollPane jScroll5;
    private javax.swing.JScrollPane jScroll6;
    private javax.swing.JTextArea jTextArea;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextArea jTextArea6;
    private javax.swing.JPanel panelJuego;
    private javax.swing.JButton tirarDados;
    // End of variables declaration//GEN-END:variables
}
